### ISSUE TITLE
Memory leak using cute_tiled

### ISSUE THREAD

**Issue by DrNicholas** [RandyGaul/cute_headers#127]
Hello, 
I am not sure if this is the right place to ask, and I checked the previous issues and did not necessarily find anything related to my issue, but this is regarding a memory leak that I have noticed in my program using cute_tiled.h.

While I was debugging my program, I noticed loading and freeing the level over and over again was causing the memory to go up, and I narrowed it down to the cute_tiled_map_t *map.

I have been looking thru the cute_tiled_free_map() function, but it looks like it is getting everything free'd. I even played with the strpool_embedded_term() function and added code to free the block tails and entry data, but that didn't seem to do anything.

I am using Windows 10, code::blocks, and using the GCC compiler that came with code::blocks. I also tried the GCC compiler from MinGW-w64 but it was the same issue.

Is there any additional information that I could give you?
Thanks

**Comment by RandyGaul** [comment]
Thanks for pointing this out! Do you happen to know the line number the allocation was coming from? How do you know where the leak is coming from? I can take a look, but if you already have debug information that could save me time before I take a look myself.

**Comment by DrNicholas** [comment]
I don't think I have any debug information, but if you know where I can find a log I will see if I can get that to you. I noticed the memory increasing with Task Manager open, about 1MB every second. I did not look inside the cute_tiled_load_map_from_file() function yet, I have only looked at the one for freeing it.

**Comment by RandyGaul** [comment]
Found the leaks, fixed them here https://github.com/RandyGaul/cute_headers/commit/e299f58aa8613b5c9f3bf5438a0d4c65006b361b

Problems was I had assumed all allocations went through a function `cute_tiled_alloc` (a special purpose paged allocator) when I wrote the map free function... Which isn't true! Many allocations go straight to `CUTE_TILED_ALLOC`, since they are unbounded arrays for the most part, and unbounded arrays don't work well for a paged allocator.

Let me know if you still have any other problems :)

**Comment by DrNicholas** [comment]
Thanks! If I find anything else I will let you know.
