### ISSUE TITLE
atlas image names in txt file cute_png.h

### ISSUE THREAD

**Issue by gearchip** [RandyGaul/cute_headers#131]
Should the names index in cp_default_save_atlas use **image->img_index** instead of **i** ?
When using **i** the file names always match the original list and become out of sync with the uv's in the text file if the atlas sorts them differently.

**Comment by RandyGaul** [comment]
You’re quite likely right! I can take a closer look in the next couple hours when I get home.

**Comment by RandyGaul** [comment]
`img_index` is the index in the user's input, which is needed since the `atlas_image_t` array is sorted by image size. I'm quite sure that the adjustment you suggested results in correct output (even though I haven't tried rendering the default atlas output yet), because the output *should* be sorted from largest to smallest if written by looping over the `atlas_image_t` array.

https://github.com/RandyGaul/cute_headers/commit/5bba82c1e58b6478bd4291d85d70189ef7dca804

Please let me know if this fixes your output!

**Comment by gearchip** [comment]
Thanks for the quick change! Yes this corrects the issue, file names and uv's match as expected now.

And by the way, great work on this collection of header files your putting together!
