### ISSUE TITLE
cute_tiled.h program compile errors with Visual Studio and MSVC

### ISSUE THREAD

**Issue by Nightlights524** [RandyGaul/cute_headers#165]
Hi Randy, thanks for all your great work! I'm using Visual Studio Community 2019 with the latest Microsoft compiler and now unfortunately a trivial program won't compile due to a couple symbol deprecation errors. Note this program works fine on Mac with Clang though.

Here is the code I tried :
```
#include <iostream>

#define CUTE_TILED_IMPLEMENTATION
#include "cute_tiled.h"

int main() 
{
    cute_tiled_map_t* map = cute_tiled_load_map_from_file("/resources/images/Overworld.json", NULL);

    std::cout << "IT WORKED!\n\n";

    return 0;
}
```
The errors are as follows:

Error	C4996	'strnicmp': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strnicmp. See online help for details.	CuteTiledTest	 C:\Users\Jon\Documents\Software Development\Repos\Nightlights524\CuteTiledTest\cute_tiled.h	947	

Error	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	 CuteTiledTest	C:\Users\Jon\Documents\Software Development\Repos\Nightlights524\CuteTiledTest\cute_tiled.h	1219

**Comment by Nightlights524** [comment]
Hi again, so I took a closer look and it appears things aren't working correctly for me on Mac with Clang 10.0.0 after all. The above program will compile and run, but when I inspect the ```map``` variable in the debugger it appears empty.

The ```cute_tiled_load_map_from_file()``` function is finding my JSON file but not loading any data into the variable. I got the same with results with VS Code and QT Creator.

Hopefully it's something silly I'm doing wrong!

**Comment by RandyGaul** [comment]
Hi there. I did see this, I’m just a little busy moving to a new place, but I can take a look soon.

The compilation error would best be fixed by adding in some macros to override default choices for common functions like strnicmp for different compilers. The second problem you posted is likely the attempted use of an unsupported feature of Tiled, or perhaps Tiled has yet again updated their JSON export and broken cute_tiled (this happens from time to time, and I’m happy to work on an update when this happens).

Post up your json file of your map so I can take a peek with the debugger. Either that, or try debugging yourself to see specifically what the problem was

**Comment by RandyGaul** [comment]
Also try reading `cute_tiled_error_reason` to see if it’s providing any clues.

**Comment by RandyGaul** [comment]
Going to close this for now. The next step is for you to put up your JSON map for either me to debug, or you can try debugging yourself. Feel free to comment here or re-open this issue if you like :)
