### ISSUE TITLE
cute_c2 How to get normal and contact point now from TOI function?

### ISSUE THREAD

**Issue by roig** [RandyGaul/cute_headers#170]
I recently saw that you have changed the c2TOI function. But I'm not sure now how to get the impact normal and the impact point. Could you explain me how to do it please? Thank you!

**Comment by RandyGaul** [comment]
This is a very good question. My apologies for changing the function! The answer is fairly complicated, so please bear with me.

The old version had numeric instability problems that I tried to side-step in a clever way... Unfortunately I didn't end up quite making it work as robustly as needed, and had to modify it to only compute a time of impact.

Once the time of impact is calculated, then it is left to the user (you, in this case) to compute any contact information (normal + contact point(s)). How to do this is an open-ended question, as nobody is really very happy with the solution. That said, here's the "canonical" solution that I recommend:

1. Shape A hits shape B at TOI
2. Move shape A to the TOI
3. Shape A and B are now very close to intersecting. So close, that it is likely numerically ambiguous whether they are intersecting or not. Even worse, if another TOI call is made, the TOI function will most likely return a time of impact of 0, which will probably lead to all kinds of bugs, like the player running through walls or getting completely stuck unable to move.
4. Instead, inflate shape B slightly by a "skin factor", a value large enough to be numerically relevant, but not large enough to be visually relevant. For example, maybe around 0.005f for some games.
5. Now run discrete collision detection on shape A and inflated shape B. Due to the skin factor the collision should not be ambiguous, and a manifold can be calculated (the normal + collision points(s)).
6. Gently press shape A away from shape B along the collision normal. Be very careful with this step! If done aggressively without care it is then possible to push shape A out of the world!
7. Now there is enough breathing room for shape A to sweep the next frame and compute a valid TOI.

**Comment by RandyGaul** [comment]
Here is an example and more information: https://github.com/RandyGaul/player2d

Please note that I haven't updated player2d in a while, and it uses the old version of c2TOI, but you can still see the NGS algorithm and the skin factor at work. NGS is just a super fancy name for step 6 in my above post.

**Comment by roig** [comment]
I will try to implement that like you said but, one question more.. Why instead of using the TOI that the function returns in order to move the shape, we pull back that TOI a bit and the we move the shape there? 

I investigated how Unreal Engine does this and I think i found something:


```
....
bool const bHadBlockingHit = MyWorld->ComponentSweepMulti(Hits, this, TraceStart, TraceEnd, InitialRotationQuat, Params);

if (Hits.Num() > 0)
{
	const float DeltaSize = FMath::Sqrt(DeltaSizeSq);
	for(int32 HitIdx=0; HitIdx<Hits.Num(); HitIdx++)
	{
		PullBackHit(Hits[HitIdx], TraceStart, TraceEnd, DeltaSize);
	}
}
....
```

And the function PullBackHit:

```
static void PullBackHit(FHitResult& Hit, const FVector& Start, const FVector& End, const float Dist)
{
	const float DesiredTimeBack = FMath::Clamp(0.1f, 0.1f/Dist, 1.f/Dist) + 0.001f;
	Hit.Time = FMath::Clamp( Hit.Time - DesiredTimeBack, 0.f, 1.f );
}

```

I think that with this, the TOI function can return the impact point using the pulled back time value. The impact normal will be the normal before the toi was pulled back. Probably I'm missing something :D.

**Comment by RandyGaul** [comment]
That pull-back hit function is actually very similar to the old function I was using. However, that strategy suffers from numeric robustness problems when the contact surface is nearly parallel with velocity, and the inflation strategy I mentioned is superior in terms of robustness due to this weakness.

> he impact normal will be the normal before the toi was pulled back.

How are you going to calculate this normal? It isn't just there for free! There needs to be a step like step 5 in my previous post.

**Comment by roig** [comment]
Ok, I will try to implement your solution and will let you know :smiley:

**Comment by RandyGaul** [comment]
Ok great! Just closing this out for no good reason, feel free to comment here or re-open if you need! :)

**Comment by roig** [comment]
Hello again, Hadn't time work on this :(.

With the previous behavior of c2TOI I had some functions to make shapecasts/sweeps etc.. for example:
```
 std::vector<HitResult> sweepMultiCollider(entt::registry& registry, const Component::Collider& collider, const Vec2& start, const Vec2& end, float rotation, const std::vector<entt::entity>& ignoredEntities);
```

As you can see I'm returning a HitResult that consists of:
```
struct HitResult {
	// Whether or not the hit was a blocking hit.
	// Due to the ability to have traces simply overlap and not stop the trace.
	bool isBlocking = false;
	// This is the "Time" of impact along the trace direction ranging from [0.0 to 1.0]. If there was no hit, this will return 1.0.
	float time = 0.f;
	// The world space location of the shape when hit.
	Vec2 shapePosition;
	// The world space location point of the hit. It is not the location of the shape.
	Vec2 impactPoint;
	// Trace direction
	Vec2 normal;
	// Normal of the hit shape
	Vec2 impactNormal;
	// The entity hit/overlaped by the trace
	entt::entity entityHit = entt::null;
	// Start position of the trace
	Vec2 start;
	// End position of the trace
	Vec2 end;
};
```

Now, my questions :P .

- If I understood you, if after a toi hit I call c2Collide with the updated toi transform in the shape is it possible to get wrong results(like getting no collision)? Is this why inflation is needed ? In other words, toi indicates always the time when it will collide ALWAYS or indicates the time just before colliding? 

- In order to calculate that HitResult information (impactNormal and impactPoint) is it sufficient to make the c2TOI and doing the steps 4 and 5? 

- Do you think it is ok to return that HitResult doing only steps 4 and 5 and then let the user decide if it wants to separate by calling or not using another function? Or for you it is better to ALWAYS separate and return a "safe" HitResult ?

**Comment by RandyGaul** [comment]
1. You want to inflate the shape so the collision functions can easily calculate a manifold. At TOI of 0 it is numerically ambiguous whether or not the shapes are colliding. This is because TOI at 0 was calculated with GJK, whereas gathering a manifold does not use GJK. Differing algorithms have different numeric sensitivities.
2. Yes, but you will need steps 5 and 6 to be able to perform steps 3 and 4 on the next frame, otherwise your next call to c2TOI will be zero.
3. You can implement this however you like! But someone will probably have to resolve the shapes at some point, otherwise they cannot call c2TOI again without getting a 0 TOI.

**Comment by roig** [comment]
Thank you Randy! Very useful information here, learning a lot!

I implemented the 1 -> 5 steps, could you take a look please and check if there is an error or if I'm doing any step wrong?

```
// A shape is the only shape that is moving
const auto movement = end - start;
const c2v deltaA = c2V(movement.x(), movement.y());
const c2x trA = c2Transform(c2V(start.x(), start.y()), (float)rotation);

// Then inside a for loop to check for others colliders...
....


const c2x trB = c2Transform(c2V(otr.position.x(), otr.position.y()), (float)Magnum::Rad(Magnum::Deg(otr.rotation)));
const c2v deltaB= c2V(0, 0); // this shape is not moving
                
// first calculate the toi of the shapes
float toi = c2TOI(
    &colA.data, colA.type, &trA, deltaA, // moving shape A
    &colB.data, colB.type, &trB, deltaB, // static shape B
    1, nullptr
);

if (toi != 1.f) {
    // We hit B!
    // Now to retrieve the manifold use what Randy Gaul suggested:
    // https://github.com/RandyGaul/cute_headers/issues/170
                    
    // First "move" A to the toi
    const c2v toiPositionA = c2V(start.x() + (deltaA.x * toi), start.y() + (deltaA.y * toi));
    const c2x trAtoi = c2Transform(toiPositionA, (float)rotation);

    // Now inflate B shape
    const float inflation = 0.005f;
    const auto colBinflated = getGenericColliderData(colliderB, {}, inflation);

    // Retrieve manifold
    // WARNING! Check c2Manifold to get the normal!! Order is important here!
    c2Manifold manifold;
    c2Collide( 
        &colBinflated.data, &trB, colBinflated.type,
        &colA.data, &trAtoi, colA.type,
        &manifold
    );

    if (manifold.count == 0) {
        spdlog::warn("c2Collide can't find a manifold for a previous toi collision!! Skiping this hit result");
    } else {
        results.push_back({});
        QueryResult &result = results.back();
        result.entityHit = oe;
        result.time = toi;
        result.impactNormal = Vec2(manifold.n.x, manifold.n.y);
        result.impactPoint = Vec2(manifold.contact_points[0].x, manifold.contact_points[0].y);
    }
}

```

What I don't understand is what exactly is the manifold.depth? If more than one contact point is returned in the manifold, is it ok to return only the first one if we don't need more precision/info?

Now going to implement the pullback function step 6.
