### ISSUE TITLE
cute_sound_pitch_plugin.h multiplies sound. 

### ISSUE THREAD

**Issue by swifton** [RandyGaul/cute_headers#174]
This is what I do:

    static float tmp_pitch = 1.0f;
    if (key_pressed(keys, SDL_SCANCODE_ESCAPE)) {
        cs_playing_sound_t* sound = cs_play_sound(assets.sound_context, assets.def);
        csp_set_pitch(sound, tmp_pitch, assets.pitch_plugin_id);
        if (tmp_pitch > 0.9f) tmp_pitch = 0.8f;
        else tmp_pitch = 1.0f;
    }

(this runs inside the game loop).

This is what I get:
https://www.dropbox.com/s/hyrmmcmj5gydcb2/cute.wav?dl=0

It looks like for pitch=1.0 it works correctly, i.e. doesn't change anything, but for other pitches (I also tried 0.5, 1.5 and 2.0) it makes the sound split into several sounds that get pitch-shifted by different amount. 

My best guess is that something went wrong between FFT and inverse FFT.

**Comment by RandyGaul** [comment]
Seems to be working just fine. If you want higher quality pitch shifting near 0.5f or 2.0f you will need to tweak the defines manually, such as `CUTE_SOUND_PITCH_QUALITY` and `CUTE_SOUND_PITCH_FRAME_SIZE`.

Another option is to use an external program to preprocess your audio into different pitches, and then save those high quality renders to disk and load them up individually, rather than shifting pitch at runtime.

```c
#define CUTE_SOUND_IMPLEMENTATION
#include "cute_sound.h"

#define CUTE_SOUND_PITCH_PLUGIN_IMPLEMENTATION
#include "cute_sound_pitch_plugin.h"

#include <stdio.h>

int main()
{
	HWND hwnd = GetConsoleWindow();
	cs_context_t* ctx = cs_make_context(hwnd, 44100, 1024 * 8, 1, NULL);
	cs_loaded_sound_t select_audio = cs_load_wav("cute.wav");
	cs_play_sound_def_t def = cs_make_def(&select_audio);
	printf("select.wav has a sample rate of %d Hz.\n", select_audio.sample_rate);

	printf("Press the 1 key!\n");
	printf("Press ESC to exit.\n");

	cs_spawn_mix_thread(ctx);

	cs_plugin_interface_t plugin = csp_get_pitch_plugin();
	cs_plugin_id_t pitch_plugin_id = cs_add_plugin(ctx, &plugin);
	float pitch = 1.0f;


	while (1)
	{
		if (GetAsyncKeyState(VK_ESCAPE)) {
			break;
		}

		if (GetAsyncKeyState(VK_UP)) {
			printf("pitch at %f\n", pitch);
			pitch += 0.1f;
		}

		if (GetAsyncKeyState(VK_DOWN)) {
			printf("pitch at %f\n", pitch);
			pitch -= 0.1f;
		}

		if (GetAsyncKeyState(0x31)) {
			cs_playing_sound_t* sound = cs_play_sound(ctx, def);
			if (sound) {
				csp_set_pitch(sound, pitch, pitch_plugin_id);
			}
		}

		Sleep(100);
	}

	cs_free_sound(&select_audio);
}
```

**Comment by RandyGaul** [comment]
Let me know if you have any other problems, and feel free to comment here or re-open this issue if neeed!

**Comment by swifton** [comment]
What do you mean by "just fine"? Have you listened to the sound that I attached? There are several sounds instead of one. And 0.8 is not that close to 0.5. And I also tried with 0.99 and got a similar result. It's not that the quality is low, it's that there is a bug.

**Comment by RandyGaul** [comment]
Do you know what algorithm is used to pitch shift? Do you know what kind of approximations are used? Do you have any idea what the expected quality should look like? Do you know that the pitch shifting sounds better with other kinds of sounds? Possibly with the single audio clip you used, the algorithm is simply failing on this kind of sound, but not other sounds, due to limitations of the algorithm itself.

The answer to these questions is probably no, meaning you likely have no idea what the sound should be like after pitch shifting.

Here are your options.
1. Use a different program offline to get high quality renders.
2. Adjust the quality defines in the pitch plugin.
3. Debug the algorithm yourself and submit a pull request.

**Comment by RandyGaul** [comment]
> Have you listened to the sound that I attached?

Yes. If you read the example code I posted above you can see it referenced your audio file.

**Comment by RandyGaul** [comment]
Ah there's one other thing that comes to mind. You can try the original code with your audio here. If there's a significant difference in the sound when using the same quality parameters, then there might be a bug: http://blogs.zynaptiq.com/bernsee/pitch-shifting-using-the-ft/

You can quite easily hook this up by replacing the code in my SIMD plugin, just to try it out.

**Comment by swifton** [comment]
Maybe I'm not explaining well? You keep talking about quality. I don't have any issues with quality, whatsoever. 

Here is my understanding of pitch shifting. You take a sound:
https://www.dropbox.com/s/4qm1hhzv7cf6bzh/original.wav?dl=0

And you change it so that the pitch is different. This is what I get with Audacity:
https://www.dropbox.com/s/9khzcmkb7u5hn1b/audacity_shifted.wav?dl=0

This is what I get with cute_sound_pitch_plugin.h:
https://www.dropbox.com/s/y2mc7efuj71a863/cute_shifted.wav?dl=0

It's not about quality. It's about the algorithm not doing what it's supposed to do. Am I misunderstanding something?

**Comment by RandyGaul** [comment]
It’s an approximate algorithm suitable for runtime. Audacity uses a very complicated and slow algorithm for offline preprocessing. They are entirely different and sound entirely different.

I have no other way to explain this to you.

**Comment by swifton** [comment]
It's not even approximately close. It's like saying that 17 is an approximation for Pi.
