### ISSUE TITLE
cute_tiled.h: 'strnicmp': The POSIX name is deprecated

### ISSUE THREAD

**Issue by aganm** [RandyGaul/cute_headers#181]
Trying to compiled cute_tiled.h in MSVC (visual studio 2019), I get this error:

```
Error	C4996	'strnicmp': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strnicmp.	cute_tiled.h	947	
```

**Comment by RandyGaul** [comment]
Ugh how annoying of an error!

Thanks for pointing this out! If you make a pull request modifying this section of code to handle this version of MSVC

```cpp
#ifndef STRPOOL_EMBEDDED_STRNICMP
    #ifdef _WIN32
        #include <string.h>
        #define STRPOOL_EMBEDDED_STRNICMP( s1, s2, len ) ( strnicmp( s1, s2, len ) )
    #else
        #include <string.h>
        #define STRPOOL_EMBEDDED_STRNICMP( s1, s2, len ) ( strncasecmp( s1, s2, len ) )        
    #endif
#endif 
```

I will happily add you to the contributor list :)

**Comment by aganm** [comment]
Done ;)

**Comment by aganm** [comment]
I added a pull request at #182

**Comment by RandyGaul** [comment]
Thanks! I was actually hoping to get a version test in there since strnicmp works on older MSVC versions, and I wanted to make sure that the underscore version doesn't break my own code -- I'm just a little slow on testing this all out since it's a little lower priority. Thank you for being patient!
