### ISSUE TITLE
cute_sound: Failed assertion when output device is disconnected (DirectSound)

### ISSUE THREAD

**Issue by codecat** [RandyGaul/cute_headers#201]
The following assertion will fail when `cs_mix` is called and the device that was in use has been disconnected:

https://github.com/RandyGaul/cute_headers/blob/0a08c5a60a1d28d1c2451cb1e75de964bcff5e82/cute_sound.h#L2284-L2294

The value of `hr` seems to be different every time. Here's 2 different values on different occasions of me reproducing this bug:

* `0x88890004`
* `0x88780096`

If I change my Windows' default output device before disconnecting the device, the assertion doesn't fail, so it seems like it's handling device changes correctly, but disconnections of the current device doesn't.

**Comment by RandyGaul** [comment]
Thanks for posting this! I've had my eye on it for a while. It will certainly be fixed, as I use cute_sound in [Cute Framework](https://github.com/RandyGaul/cute_framework). It's just a bit low priority for now. Though, if anyone needs this fixed sooner rather than later let me know and I can re-prioritize.

**Comment by RandyGaul** [comment]
This should be fixed with version 2.0. DirectSound requires some extra functions to be called to restore device and such, much like DirectX 9.
