### ISSUE TITLE
cute_sound does not play in Windows when the window loses focus

### ISSUE THREAD

**Issue by mijagourlay** [RandyGaul/cute_headers#235]
cute_sound does not play in Windows when the window loses focus.

The problem can be resolved by making a change in cs_make_context, where the secondary buffer is created:

		LPDIRECTSOUNDBUFFER secondary_buffer;
		bufdesc.dwSize = sizeof(bufdesc);
		bufdesc.dwFlags = DSBCAPS_GLOBALFOCUS ; // MJG changed from 0 so audio can play even when window loses focus

Changing the DSBUFFERDESC flags to include DSBCAPS_GLOBALFOCUS  lets the sound keep playing when the window loses focus.

**Comment by RandyGaul** [comment]
Thanks for noting this! I think I do prefer the behavior of not playing out of focus, but since the source is easily modified anyone can adjust this behavior themselves. I considered making this a part of the public API, but I didn't feel it was high priority enough.

However, if anyone wants to make a public API for this I would probably accept a pull request (not specifically you @mijagourlay, but am writing this for anyone else viewing in the future) :)

**Comment by printablealice** [comment]
Thanks for this! :)
