### ISSUE TITLE
Is there concave polygon support in tinyc2?

### ISSUE THREAD

**Issue by Thomasdb05** [RandyGaul/cute_headers#317]

**Comment by RandyGaul** [comment]
No concave support because there aren't simple and good algorithms for concave shapes. Instead I suggest changing the design of your game so you don't need concave shapes, or try using another tool to convert concave shapes to a decomposition of convex shapes. There are lots of algorithms to do this out there. Try searching for "2d convex decomposition".

**Comment by Thomasdb05** [comment]
Ah yes I read about that, I struggled to find a good library with an implementation of this as concave shapes are crucial for my project, but I'll keep looking, thanks!

**Comment by RandyGaul** [comment]
Let us know if you find a good one!
